### ISSUE TITLE
Possible errors with Storage class

### ISSUE THREAD

**Issue by joelczk** [AY2021S1-CS2113T-W12-3/tp#136]
<img width="400" alt="bug2" src="https://user-images.githubusercontent.com/42378287/97384853-87e1f800-190b-11eb-8940-47039cdf3a3b.PNG">

1. [ ] Visibility of classes and variables not in properly format (red)
2. [ ] Class names not in standard format (blue), which I think is because of the fact that Plant UML is used to create this diagram. (Refer to https://github.com/nus-cs2113-AY2021S1/forum/issues/112)

**Comment by judowha** [comment]
Can someone help me change the diagram format, I dont know why my intellij can not open the class diagrams

**Comment by BenardoTang** [comment]
Sure! i changed it abit and it looks like this:
![image](https://user-images.githubusercontent.com/60357492/98429827-1f053780-20e4-11eb-9082-0e9dc1635c0b.png)
i'll try to merge the pr, hopefully you can access it after that

**Comment by joelczk** [comment]
All the errors are compiled and listed together in #149 already, if all of you are not aware

**Comment by judowha** [comment]
Benardo thank you so much!!!! B God!!

**Comment by BenardoTang** [comment]
Thanks for the heads-up @joelczk and thanks J-God @judowha
