### ISSUE TITLE
the Time Left Today can be negative

### ISSUE THREAD

**Issue by judowha** [AY2021S1-CS2113T-W12-3/tp#146]
For the time left today, I think the minimum value should be 0. But now it can show a negative value
![bug](https://user-images.githubusercontent.com/60347669/97535545-c2748f00-19f6-11eb-93cf-6c3f5565d95b.png)

**Comment by BenardoTang** [comment]
I think its okay to leave the time left today to be negative if the user overshot his watch time. I included a line inside (Your watch time deficit will be highlighted below :( ) To let the user know why there is a negative number.

**Comment by judowha** [comment]
> I think its okay to leave the time left today to be negative if the user overshot his watch time. I included a line inside (Your watch time deficit will be highlighted below :( ) To let the user know why there is a negative number.

emmmmm, that makes sense. Then we just leave it. Thanks, Benardo!
