### ISSUE TITLE
UpdateShowSeasonCommand

### ISSUE THREAD

**Issue by judowha** [AY2021S1-CS2113T-W12-3/tp#199]
For the UpdateShowSeasonCommand, It allows users to add one optional argument to update episodes at the same time. But the optional argument is not indicated in the UG and we also have another UpdateShowEpisodeCommand to update the episode. Should we keep it or remove it?
![QQ截图20201105081357](https://user-images.githubusercontent.com/60347669/98181867-4c64b080-1f3f-11eb-9574-f27f6586d90a.png)

**Comment by BenardoTang** [comment]
Good catch - we should either include in dg or remove the function

**Comment by shikai-zhou** [comment]
Will update the DG
