### ISSUE TITLE
Check correct number of episodes input

### ISSUE THREAD

**Issue by jazhten** [AY2021S1-CS2113T-W12-3/tp#37]
Check correct number of episodes input when adding new show or other functions related to the int[] numEpisodes array anywhere.

**Comment by shikai-zhou** [comment]
This is done for add

**Comment by BenardoTang** [comment]
For episode and season command, can we include a catch to make sure correct number of episodes input?

For now, i can move the episode number to 100 even tho i set the show to have only 10 episodes (same for season)

**Comment by shikai-zhou** [comment]
What was the input you used, so I can replicate the problem
