### ISSUE TITLE
Clarification on product scope for students

### ISSUE THREAD

**Issue by BenardoTang** [AY2021S1-CS2113T-W12-3/tp#73]
Are we including the feature that Students are able to track their webcast/lectures on watchnext? If yes then we can include this selling point in our developer guide/user guide and product pitch/demo

Boss, for your approval please

**Comment by jazhten** [comment]
Yea, I think we should include it in the UG so it'll be easier to use for the pitch/demo. Don't think it's necessary for the DG, maybe a quick note in the abstract or intro about the student part would be sufficient.
